[정수론] 9월 3일
Altu-Bitu-7/Altu-Bitu-LeeHongYeon pull request #4
Opened 2024-09-03 02:58 UTC by HongYeonLee

### 인적사항

학번: 2371049
이름: 이홍연

### 과제제출

기존 제출: 1735,  2840, 9020

2024-09-08 05:31 UTC, avocado8 requested changes
6588(p1)
과제 문제는 9020번이 아닌 6588번입니다!! ( https://www.acmicpc.net/problem/6588 )
문제 이름이 동일해서 잘못 제출해주신 것 같아요 😢 수정하신 뒤 리뷰어를 다시 호출해주시면 코드확인 후 출석처리 해드리겠습니다!

2024-09-08 11:44 UTC, avocado8 reviewed
6588(p3)
홍연님 안녕하세요 :3 수정 확인하였고 6588번 코드리뷰 드렸습니다. 튜터링 초반이라 출석 처리해드렸으나 앞으로는 깃허브 리드미에서 꼼꼼히 확인하신 후 과제 올려주세요! ☺️
질문이 있으시다면 언제든 편히 리뷰어를 호출해주세요~

2024-09-08 11:44 UTC, avocado8 commented on 03_정수론/필수/BOJ_6588.cpp
> +#define MAX 1000000 // 3부터 최대 100만까지의 수들 중 소수 판별 | 500만은 오버플로우 발생하니 주의...
상수 선언 좋아요~

2024-09-08 11:44 UTC, avocado8 commented on 03_정수론/필수/BOJ_6588.cpp
> +vector<bool> getPrimes()
정수론 이론을 잘 이해한 로직과 꼼꼼한 주석까지 아주 좋습니다 ☺️👍

2024-09-08 11:44 UTC, avocado8 commented on 03_정수론/필수/BOJ_6588.cpp
> +        cout << n << " = " << a << " + " << b << "\n";
p3. 입력과 출력을 함수에서 관리하게 될 경우, 함수의 용도가 굉장히 불명확해져요. 특히 함수화를 하는 이유는 특정 코드를 계속 반복해서 쓸 수 있도록 (재사용성을 높임) 하기 위함인데, 입력과 출력을 같이 해버리면 해당 함수를 다른 곳에서  또 쓰기도 애매해지죠! 따라서 입력과 출력은 메인에서만 하도록 권장드리고 있습니다!! ✨✨

2024-09-08 11:44 UTC, avocado8 approved these changes

2024-09-10 01:45 UTC, merged

2024-09-10 01:47 UTC, ruruisryu reviewed
1735번 너무 잘 풀어주셨습니다! 몇가지 코멘트 남겨드렸으니 확인부탁드립니다. 수고하셨어요~

2024-09-10 01:47 UTC, ruruisryu commented on 03_정수론/필수/BOJ_1735.cpp
> +}
findGcd 함수 너무 잘 구현해주셨어요!

2024-09-10 01:47 UTC, ruruisryu commented on 03_정수론/필수/BOJ_1735.cpp
> +void add(int n1, int m1, int n2, int m2)
함수화 굿!

2024-09-10 01:47 UTC, ruruisryu commented on 03_정수론/필수/BOJ_1735.cpp
> +
gcd가 1인 경우에는 c1과 c2를 gcd로 나눠봤자 나누지 않은 상황과 다를 바 없으니 if 조건이 있든 없든 똑같은 결과를 낼 것 같네요!
```
m3 /= gcd;
n3 /= gcd;
```
이 부분만 남겨두어도 괜찮을 것 같습니다. ☺️

2024-09-10 01:47 UTC, ruruisryu commented on 03_정수론/필수/BOJ_1735.cpp
> +    cout << n3 << " " << m3;
p3. 입력과 출력을 함수에서 관리하게 될 경우, 함수의 용도가 굉장히 불명확해져요. 입력과 출력을 같이 해버리면 해당 함수를 다른 곳에서  또 쓰기도 애매해져 재사용성이 떨어집니다! 따라서 입력과 출력은 메인에서만 하도록 권장드리고 있습니다~

2024-09-10 12:42 UTC, kimeunsom reviewed
2840 구현 문제의 복잡한 예외 상황들을 잘 처리해주셨네요 함수화도 너무 깔끔합니다 ~ 고생하셨습니다 !